POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "title": "test requestLogger middleware",
  "author": "hugu",
  "url": "www.meizizi.com",
  "likes": 22
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "title": "test errorHander middleware",
  "author": "hugu",
  "url": "www.meizizi.com",
  "likes": "likes should not be a string"
}

###
DELETE http://localhost:3003/api/blogs/62e7dfd3913ef16806d9a1a8

###
PUT http://localhost:3003/api/blogs/62f11b5fac4a204942ae529a
Content-Type: application/json

{
  "title": "test errorHander middleware",
  "author": "hugu",
  "url": "www.meizizi.com",
  "likes": 809
}

###
PUT http://localhost:3003/api/blogs/62f11b5fac4a204942ae529a
Content-Type: application/json

{
  "title" : "wuhu",
  "author": "hugu",
  "url": "",
  "likes": 777
}

